/*--------------------------------------------------------------------------
Author:         Moon Cui (Perficient)
Description:    This class maintain all constant values for other classes in Community.
History
2/2/2016    Moon Cui    Initial version
3/10/2016   Moon Cui    Changed CASE_QUEUE_DEV_NAME from 'Customer_Community_Case' to 'NewSupportCases'
----------------------------------------------------------------------------*/
public class CommunityConstants {
    //Case
    public static final String CASE_CUSTOMER_RECORDTYPE_NAME = 'Customer Community Case';
    public static final String CASE_QUEUE_DEV_NAME = 'NewSupportCases';
    public static final String CASE_ORIGIN_WEB = 'Web';
    //Feedback
    public static final String FEEDBACK_QUEUE_DEV_NAME = 'Community_Feedback';
}