@isTest(SeeAllData=True)
private class contractBillingItems_test {

    static testMethod void myUnitTest() {
        
        /*Profile pro = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        
        UserRole role = [SELECT Id From UserRole WHERE Name = 'Director of Sales'];
        
        User u_testMethodUser = new User(alias = 'testMeth', email = 'testMethodUser@salesforce.com',
        	emailencodingkey = 'UTF-8', lastname = 'Test Method User', languagelocalekey = 'en_US',
        	localesidkey = 'en_US', profileid = pro.Id, 
        	timezonesidkey = 'America/Los_Angeles', username = 'testMethodUser@salesforce.com',
        	UserRoleId = role.Id);
        	
        insert u_testMethodUser;
        
        //UserRoleId
        
        System.runas(u_testMethodUser) {
        	
        	
        }*/
    }
}