public with sharing class handler_OLI {
	
	// AFTER DELETE
	public static void afterDelete() {
		
		
	}
	
	// AFTER INSERT
	public static void afterInsert() {
		
		
	}
	
	// AFTER UNDELETE
	public static void afterUndelete() {
		
		
	}
	
	// AFTER UPDATE
	public static void afterUpdate() {
		
		
	}
	
	// BEFORE DELETE
	public static void beforeDelete() {
		
		
	}
	
	// BEFORE INSERT
	public static void beforeInsert() {
		
		
	}
	
	// BEFORE UPDATE
	public static void beforeUpdate() {
		
		
	}	
}